/*
 * Copyright 2022 Joaquin Osvaldo Rodriguez
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.meritoki.prospero.desktop.view.panel;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.awt.event.MouseMotionListener;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import org.meritoki.prospero.desktop.view.menu.GridPopupMenu;
import org.meritoki.prospero.library.model.Model;
import org.meritoki.prospero.library.model.node.Spheroid;
import org.meritoki.prospero.library.model.node.Variable;

/**
 *
 * @author jorodriguez
 */
public class CameraPanel extends javax.swing.JPanel
		implements KeyListener, MouseListener, MouseMotionListener, Runnable {

	private static final long serialVersionUID = 1L;
	static Logger logger = LogManager.getLogger(CameraPanel.class.getName());
	protected GridPopupMenu menu;
	public Model model;
	public double factor = 1.5;
	protected int xDelta, yDelta;
	protected int azimuth = 0;
	protected int elevation = 0;
	public Dimension dimension;

	/**
	 * Creates new form CameraPanel
	 */
	public CameraPanel() {
		this.initComponents();
		this.addKeyListener(this);
		this.addMouseListener(this);
		this.addMouseMotionListener(this);
		this.setSize(1024, 512);
	}

	public void setModel(Model model) {
		this.model = model;
		this.menu = new GridPopupMenu(this.model);
	}

	@Override
	public void paint(Graphics graphics) {
		super.paint(graphics);
		logger.debug("paint(" + (graphics != null) + ")");
		this.dimension = this.getSize();
		graphics.setColor(Color.white);
		graphics.fillRect(0, 0, this.getWidth(), this.getHeight());
		graphics.translate((int) (this.getWidth() / 2.0), (int) (this.getHeight() / 2.0));
		if (this.model != null && this.model.node != null) {
			Variable node = this.model.node;
			if (node != null) {
				try {
					node.paint(graphics);
				} catch (Exception e) {
					e.printStackTrace();
				}
			}
		}
	}

	@Override
	public void keyTyped(KeyEvent e) {

	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
		this.setLayout(layout);
		layout.setHorizontalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 400, Short.MAX_VALUE));
		layout.setVerticalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 300, Short.MAX_VALUE));
	}// </editor-fold>//GEN-END:initComponents

	@Override
	public void run() {
		// TODO Auto-generated method stub

	}

	@Override
	public void mouseDragged(MouseEvent e) {
		if (this.model != null && this.model.node != null) {
			int xDelta = e.getX();
			int yDelta = e.getY();
			this.azimuth -= xDelta - this.xDelta;
			this.elevation -= yDelta - this.yDelta;
			if(model.node instanceof Spheroid) {
				Spheroid s = (Spheroid)this.model.node;
				s.setAzimuth(this.azimuth);
				s.setElevation(this.elevation);
			}
			this.xDelta = xDelta;
			this.yDelta = yDelta;
			this.repaint();
			e.consume();
		}
	}

	@Override
	public void mouseMoved(MouseEvent arg0) {
		// TODO Auto-generated method stub

	}

	@Override
	public void mouseClicked(MouseEvent arg0) {
		this.requestFocus();

	}

	@Override
	public void mouseEntered(MouseEvent arg0) {
		// TODO Auto-generated method stub

	}

	@Override
	public void mouseExited(MouseEvent arg0) {
		// TODO Auto-generated method stub

	}

	@Override
	public void mousePressed(MouseEvent e) {
		this.xDelta = e.getX();
		this.yDelta = e.getY();
		e.consume();
		if (e.isPopupTrigger())
			showSavePopupMenu(e);
	}

	@Override
	public void mouseReleased(MouseEvent e) {
		if (e.isPopupTrigger())
			showSavePopupMenu(e);

	}

	@Override
	public void keyPressed(KeyEvent e) {
//		logger.info("keyPressed("+e+")");
		if (this.model != null && this.model.node != null) {
			if(model.node instanceof Spheroid) {
				Spheroid s = (Spheroid)this.model.node;
				double scale = s.projection.scale;
				if (e.isControlDown()) {
					switch (e.getKeyChar()) {
					case '+': {
						s.setScale(scale * 2);
						this.repaint();
						break;
					}
					case '-': {
						s.setScale(scale / 2);
						this.repaint();
						break;
					}
					}
				}
			}
		}
	}

	@Override
	public void keyReleased(KeyEvent arg0) {
		// TODO Auto-generated method stub

	}

	private void showSavePopupMenu(MouseEvent e) {
		if (menu != null)
			menu.show(e.getComponent(), e.getX(), e.getY());
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	// End of variables declaration//GEN-END:variables
}
//graphics.fillRect(0, 0, (int)(this.getWidth()), (int)(this.getHeight()));
//graphics.translate((int) (this.getWidth() / 2.0), (int) (this.getHeight() / 2.0));
