/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.meritoki.app.desktop.prospero.view.panel;

import java.util.List;

import javax.swing.JTabbedPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

import com.meritoki.library.prospero.model.Model;
import com.meritoki.library.prospero.model.plot.Plot;
import com.meritoki.library.prospero.model.table.Table;

/**
 *
 * @author jorodriguez
 */
public class TablePanel extends javax.swing.JPanel implements Runnable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -6800902203212169286L;
	public Model model;
	public TableModel tableModel;
	public JTabbedPane tabbedPane = new JTabbedPane();
    /**
     * Creates new form TablePanel
     */
    public TablePanel() {
		Thread thread = new Thread(this);
		thread.start();
    }
    
    public TablePanel(TableModel tableModel) {
    	this.tableModel = tableModel;
    	initComponents();
    	this.table.setModel(this.tableModel);
		this.revalidate();
		this.repaint();
    }
    
//    public void paint(Graphics g) {
//    	
//    }
    
	public void setModel(Model model) {
		this.model = model;		
	}
	
	public void test() {
		if (this.model != null) {
			System.out.println("init() this.model != null");
			this.tabbedPane.removeAll();
	        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
	        this.setLayout(layout);
	        layout.setHorizontalGroup(
	            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addComponent(this.tabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 716, Short.MAX_VALUE)
	        );
	        layout.setVerticalGroup(
	            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addComponent(this.tabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 362, Short.MAX_VALUE)
	        );
			try {
				
					TablePanel plotPanel = new TablePanel(new DefaultTableModel());
					this.tabbedPane.addTab("test",plotPanel);
				
			} catch (Exception e) {
				e.printStackTrace();
			}
			this.add(this.tabbedPane);
			this.revalidate();
			this.repaint();
		}
	}
	
	public void init() {
		if (this.model != null) {
			this.tabbedPane.removeAll();
	        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
	        this.setLayout(layout);
	        layout.setHorizontalGroup(
	            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addComponent(this.tabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 716, Short.MAX_VALUE)
	        );
	        layout.setVerticalGroup(
	            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
	            .addComponent(this.tabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 362, Short.MAX_VALUE)
	        );
			List<Plot> plotList;
			try {
				plotList = this.model.getPlotList();
				for (Plot plot : plotList) {
					for(Table table: plot.tableList) {
						TablePanel tablePanel = new TablePanel(table.tableModel);
						this.tabbedPane.addTab(table.name,tablePanel);
					}
				}
			} catch (Exception e) {
				e.printStackTrace();
			}
			this.add(this.tabbedPane);
			this.revalidate();
			this.repaint();
		}
	}

	@Override
	public void run() {
		while (true) {
			try {
				this.init();
				Thread.sleep(10000);
			} catch (InterruptedException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
		}
	}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(table);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 716, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 362, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
