
title: Meritoki Prospero
logo: ./Splash.png
description: Prospero is a simple and extensible interface for visualization of spatial temporal information with the possibility of applying statistical analysis
show_downloads: true
theme: jekyll-theme-minimal
#google_analytics: UA-176777850-1
